Adds args for intermediate objects
iiif-prezi/iiif-prezi3 pull request #139
Opened 2022-12-09 19:20 UTC by helrond

Adds arguments for Annotation and AnnotationPage.

I didn't add **kwargs for `AnnotationHelpers.add_annotation` because we're already passing in a pre-fab Annotation object, so since we're not creating an Annotation from scratch it makes less sense to do that (IMO). Happy to be contradicted though.

Fixes #111

2022-12-11 14:09 UTC, digitaldogsbody requested changes
Looks great, thanks Hillel :) I agree with the rationale for not passing `**kwargs` to `add_annotation`.

Can we add the `anno_page_id` also to the `make_annotation` helper so that it can be passed through even when you don't have an Annotation object pre-created, when that function calls the now-fixed `add_annotation`?

2022-12-12 12:33 UTC, giacomomarchioro approved these changes
That looks very good to me! That are only two observations that come to my mind but probably is better to address them in a separate issue:

1.  in the case of a Canvas you can add an Annotation to the `items` or to the `annotations` list. How can you differentiate? In this case, the Annotation helper is inserting by default the annotation to the annotations list.
2. shall we provide the ability to set the format and the id of the body as args of the function, in case I want to show lower resolution or rotated images in the create_canvas_from_iiif?

2022-12-14 03:53 UTC, digitaldogsbody commented
>     1. in the case of a Canvas you can add an Annotation to the `items` or to the `annotations` list. How can you differentiate? In this case, the Annotation helper is inserting by default the annotation to the annotations list.

I think that `make_canvas`/`add_canvas` should cover the first, and `make_annotation`/`add_annotation` the second.
 
>     2. shall we provide the ability to set the format and the id of the body as args of the function, in case I want to show lower resolution or rotated images in the create_canvas_from_iiif?

This is a good idea - maybe also a separate helper targeted at the annotation body `SpecificResource` instance that allows manipulation after (in the manner of the `set_hwd` helpers)?

2022-12-14 03:53 UTC, digitaldogsbody approved these changes

2022-12-24 17:31 UTC, merged